name: VSIX

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/vsix.yml'
      - '!src/GUI/**/*'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  VERSION: 2.6.${{ github.run_number }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update Version
      run: |
        ((Get-Content -Path GUI/EFCorePowerTools/source.extension.vsixmanifest -Raw) -Replace "2.5.0", "${{ env.VERSION }}") | Set-Content -Path GUI/EFCorePowerTools/source.extension.vsixmanifest
        ((Get-Content -Path GUI/PowerToolsExtensionPack/source.extension.vsixmanifest -Raw) -Replace "2.5.0", "${{ env.VERSION }}") | Set-Content -Path GUI/PowerToolsExtensionPack/source.extension.vsixmanifest
      working-directory: src
      shell: pwsh

    - name: Restore
      run: dotnet restore EFCorePowerTools.sln
      working-directory: src

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3

    - name: Build
      run: msbuild EFCorePowerTools.sln /property:Configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
      working-directory: src

    - name: Move build output
      run: |
        mv src/GUI/EFCorePowerTools/bin/Release/EFCorePowerTools.vsix EFCorePowerTools-${{ env.VERSION }}.vsix
        mv src/GUI/PowerToolsExtensionPack/bin/Release/PowerToolsExtensionPack.vsix PowerToolsExtensionPack-${{ env.VERSION }}.vsix      

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: |
          *.vsix

    - name: Publish to Open VSIX Gallery
      if: github.ref == 'refs/heads/master'
      run: |
        $ErrorActionPreference='Stop'
        (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
        Vsix-PushArtifacts | Vsix-PublishToGallery 
      shell: pwsh
      continue-on-error: false
